services:
  web:
    build: .
    container_name: identity-recognition-web
    ports:
      - "33002:80"
    networks:
      - identity-recognition-network

networks:
  identity-recognition-network:
    external: true